@echo off

set ADDON_NAME=waddon

:: IDL Definition of your addon
set IDL=%ADDON_NAME%.idl

:: Main entrypoint
set IN=src/%ADDON_NAME%.cpp
:: Header definition of exports from main entrypoint
set HEADER=src/%ADDON_NAME%.hpp

:: Out file
set OUT=%ADDON_NAME%.wasm

:: Bindings that will be autogenerated by lua-webidl
:: Deleted after this script finishes.
set BINDS=bindings.cpp

:: Stack Size
set STACK=6000000

:: For wasi-sdk path, see https://github.com/WebAssembly/wasi-sdk
:: This is necessary to use the standard library headers with your addons
set SYSROOT=%WASI_SDK_PATH%/share/wasi-sysroot
set CLANG=%WASI_SDK_PATH%/bin/clang++
set EMULATE=-D_WASI_EMULATED_SIGNAL -lwasi-emulated-signal

:: Create webassembly friendly bindings (--cpp mode is the only one supported as of now)
:: This isn't *necessary* if you want to make bindings with Rust or something
:: Note that the batchfile hangs here because.. it doesn't close properly? Will likely make an issue for this
lua-webidl %IDL% %BINDS% %HEADER% --libmode --cpp

:: Compile the newly created bindings, your project into .wasm
%CLANG% %IN% %BINDS% tiny-json/tiny-json.c --sysroot=%SYSROOT% --target=wasm32-wasi -O3 -Wl,-z,stack-size=%STACK%,--allow-undefined,-export-dynamic -fvisibility=hidden -o %OUT% %EMULATE%

:: Turn the .wasm output into lua!
wasm2lua %OUT% %ADDON_NAME%.lua -b %IDL% --libmode --pureLua --m3